

class BackgroundJobsType:
    NFT = 'NFT'
    BOX = 'BOX'
    REFERRAL_COMMISSION = 'REFERRAL_COMMISSION'
    BOX_REFERRAL_COMMISSION = 'BOX_REFERRAL_COMMISSION'

class Chains:
    BSC = "BSC"
    POLYGON = "POLYGON"
    AVAX = "AVAX"
    BOBA = "BOBA"